version: '3'
services:
  mongo-container:
    container_name: mongo_container
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod
  app:
    container_name: app_container
    image: python:3.9
    working_dir: /app
    volumes:
      - ./assets:/app/assets
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo-container
    command:
      - sh
      - -c
      - |
        pip install -r /app/reqs/requirements.txt
        python main.py

volumes:
  assets:
